### ISSUE TITLE
islemtipi

### ISSUE THREAD

**Issue by ardaorkin** [eraycetinay/node-nestpay#7]
Selamlar.
Bu modülü kullanırken **islemtipi** adlı parametrenin olmadığını gördüm. Kendim elle bu parametreyi ekledim ama repoya da yaptıklarımı merge etmek isterim sizin için de uygunsa.

**Comment by eraycetinay** [comment]
https://opensource.com/article/19/7/create-pull-request-github

**Comment by ardaorkin** [comment]
Teşekkür ederim.

**Comment by ardaorkin** [comment]
[Pull request'i](https://github.com/eraycetinay/node-nestpay/pull/8) attım.
